### ISSUE TITLE
on current route , add 'active' class

### ISSUE THREAD

**Issue by kuatsure** [asross/dynamic-link#2]
would love to have a class applied when a user is on the route that the `dynamic-link` goes to. similar to what `link-to` does.

**Comment by asross** [comment]
That sounds good to me. Will give it a shot sometime soon!

**Comment by asross** [comment]
I made a pull request to address this, let me know if it does what you need: https://github.com/asross/dynamic-link/pull/3

**Comment by kuatsure** [comment]
ooh :( just saw this, over the coming days I'll definitely run this change through and see :) thanks!

**Comment by asross** [comment]
Great! Feel free to open another issue if it's not what you had in mind :)
