### ISSUE TITLE
Multiple {{dynamic-link}} in template supported?

### ISSUE THREAD

**Issue by eharrow** [asross/dynamic-link#8]
I have an odd issue where I am setting the query params dynamically which seems to generate the link href correctly however when I click the link the url that is transitioned to is always the url of the last href {{dynamic-link}} instance on the page.

Is this helper stateless?

e.g. template.hbs

    {{#dynamic-link route='sysmngt.devices' queryParams=(dynamic-link-params "groups" "groups1")}} groups1{{/dynamic-link}}
    {{#dynamic-link route='sysmngt.devices' queryParams=(dynamic-link-params "groups" "groups2")}} groups2{{/dynamic-link}}

and dynamic-link-params.js helper:

import Ember from 'ember';

const {Helper} = Ember;

/**
 * A helper to convert a name value pair to a an object that is suitable for the dynamic-link component
 * @param {array} params
 * @returns {{}}
 */
export function dynmicLinkParams(param) {
  const paramsObj = {};
  if (params.length === 2) {
    paramsObj[params[0]] = encodeURI(params[1]);
  }
  Ember.Logger.debug(`paramsObj=${JSON.stringify(paramsObj)}`);
  return paramsObj;
}

export default Helper.helper(dynmicLinkParams);

**Comment by asross** [comment]
Hmm, interesting issue. I'm pretty sure the component itself is stateless -- I've used multiple per page with different `queryParams` before.

Is it possible that your `dynamic-link-params.js` isn't stateless, e.g. somehow the second time you call it, it modifies the first `paramsObj` you return? You could also try exposing the params objects as properties on the parent component/controller.

**Comment by eharrow** [comment]
That does not seem to be the problem as the mouseover and generated src (viewed in chrome) show distinct and expected links.  It seems to be in the transition.

**Comment by eharrow** [comment]
I forked the component and added some debug in the transitionRoute() and can confirm that the link href is fine but queryparams are always the ones for the last instance in the template.

**Comment by asross** [comment]
Cool, thanks for all this investigation. I will take a look at it soon and try to reproduce/fix it (although if you fix the issue in your fork, feel free to make a PR). Just to clarify, in those debug statements are you seeing the wrong values in `routeArguments`/`routingArguments`, or is the issue that the `transitionTo` call does not perform correctly?

Also, what version of Ember are you running?

**Comment by eharrow** [comment]
Ember	2.12.1
Ember Data	2.12.2
jQuery	3.2.1

I think the transitionTo is ok actually but the `routingArguments` and `routeArguments` that it passes to the router.transitionTo() seem to be incorrect even though the generated urls _appear_ ok.  I have tried to add debug to the href computed prop but that results in an assert error from ember.

**Comment by eharrow** [comment]
The following might be related - multiple ember component instances on a page https://github.com/octobercms/october/issues/737

**Comment by asross** [comment]
Ok, cool. I wonder if the problem could have something to do with a version incompatibility -- I'm not actively developing any apps in Ember right now, so I think this library hasn't been run against 2.12 or 2.13. And it looks like the dependencies are slightly out of date as well.

 I'm a bit busy today but I'll try to get this resolved soon. If you're able to create a test case in your fork that reproduces the issue (and if it only fails on recent versions), then that would definitely speed things up. If you make partial progress that isn't ready for a full PR, you can make a PR into the `queryparams-fix` branch and we can merge to master once we've fully resolved the issue.

**Comment by asross** [comment]
I'm assuming you've probably moved on from this now, but I have a branch where I've fully upgraded Ember CLI and, on all the tests, added a second `dynamic-link` to the end of the page. I'll push this up soon, but I don't think it will solve your problem -- the tests still pass even though there are now two links on the page.

**Comment by eharrow** [comment]
I'm afraid I could not make it work so went back to using the OOTB link-to helper in the template and figured out how to make it work using https://discuss.emberjs.com/t/passing-dynamic-query-params-as-an-object-in-link-to-helper/9136/3

**Comment by asross** [comment]
Gotcha. Glad you were able to get it to work somehow, and thanks again for reporting this.
